# Generated by Django 4.1.7 on 2023-03-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshoplist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='image',
            field=models.ImageField(default='coffee_shop_images/default.jpg', upload_to='coffee_shop_images/'),
        ),
    ]
