# Generated by Django 4.1.7 on 2023-03-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafesubmission', '0003_cafesubmission_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='cafesubmission',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='cafesubmission',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='cafesubmission',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='cafesubmission',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafesubmission',
            name='hours',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafesubmission',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cafesubmission',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cafesubmission',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cafesubmission',
            name='image',
            field=models.ImageField(default='coffee_shop_images/default.jpg', upload_to='coffee_shop_images/'),
        ),
        migrations.AlterField(
            model_name='cafesubmission',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cafesubmission',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
