# Generated by Django 4.1.7 on 2023-03-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafesubmission', '0004_rating_remove_cafesubmission_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='cafesubmission',
            name='approved',
            field=models.BooleanField(null=True),
        ),
    ]
